spring.application.name=backend
spring.data.mongodb.uri=mongodb://localhost:27017/smarttimetrack

app.company.latitude=48.8566
app.company.longitude=2.3522
app.company.allowedRadius=50
app.qrcode.dailySecret=SECRET_QR_CODE_123

# JWT secret key (must be 256 bits minimum)
jwt.secret=your_super_secret_key_which_must_be_very_long_and_secure_to_use_hs256_algorithm_for_jwt
jwt.expirationMs=86400000
